# Generated by Django 3.0.5 on 2025-03-18 07:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Pinac', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='red', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='cotton', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='neck_type',
            field=models.CharField(blank=True, choices=[('CREW', 'Crew'), ('V_NECK', 'V-Neck'), ('SCOOP', 'Scoop')], max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('CASUAL', 'Casual'), ('FORMAL', 'Formal'), ('ACTIVE', 'Active')], max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='pattern',
            field=models.CharField(blank=True, choices=[('SOLID', 'Solid'), ('STRIPED', 'Striped'), ('FLORAL', 'Floral'), ('GRAPHIC', 'Graphic')], max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='S', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sleeve_length',
            field=models.CharField(blank=True, choices=[('SHORT', 'Short'), ('LONG', 'Long'), ('EXTRA_LONG', 'Extra Long')], max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
