# Generated by Django 3.0.5 on 2025-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20250318_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_image/default.jpg', upload_to='product_image/'),
        ),
    ]
