# Generated by Django 3.0.5 on 2025-03-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20250318_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
