# Generated by Django 3.0.5 on 2025-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20250318_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dominant_colors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
